//
// Created by Ophélien DUPARC on 09/03/2023.
//

#ifndef CMESSENGER_CMESSEGER_COMMON_H
#define CMESSENGER_CMESSEGER_COMMON_H

#define CMESSENGER_MAX_LENGHT 255

#endif //CMESSENGER_CMESSEGER_COMMON_H
